#!/bin/sh
# @@@LICENSE
#
#      Copyright (c) 2008-2012 Hewlett-Packard Development Company, L.P.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# LICENSE@@@

ENV=$(env)
echo "$0: $ENV" | logger -s

case "$runlevel" in
	U)
		CAUSE="Update";
		;;
	H)
		CAUSE="HardReset";
		;;
	R|6)
		CAUSE="Reboot";
		;;
	S|0)
		CAUSE="Shutdown";
		;;
esac

if ls-monitor --list | grep -q com.palm.power; then
    echo "$0: Shutting down apps then services because of $CAUSE" | logger -s
    RESULT=$(luna-send -n 1 luna://com.palm.power/shutdown/initiate "{\"cause\":\"$CAUSE\"}" 2>&1)
    echo "$0: Result: $RESULT" | logger -s
else
    echo "$0: com.palm.power service not running" | logger -s
fi
